server:
  port: 8083

cpo:
  services:
    enhancer:
      uri: http://localhost:8084
    notifier:
      uri: http://localhost:8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/processor
    username: processor
    password: Ak4X6HYmZmM5pfd7hBtyj
    hikari:
      maximum-pool-size: ${PG_MAX_POOL_SIZE:5}
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true