### metrics ###
spring.application.name=cpo-processor
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoints.jmx.exposure.include=*