cpo:
  services:
    auth:
      uri: ${AUTH_URL}
    processor:
      uri: ${PROCESSOR_URL}

spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: GTW

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
    jmx:
      exposure:
        include: "*"