server:
  port: 8086

spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/notifier
    username: notifier
    password: swBAetMEoAUYffo3mzKY7
    hikari:
      maximum-pool-size: ${PG_MAX_POOL_SIZE:5}
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect