server:
  port: 8084

spring:
  main:
    banner-mode: off
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/enhancer
    username: enhancer
    password: Qvr4gthjdW2JBEAZda5yv
    hikari:
      maximum-pool-size: ${PG_MAX_POOL_SIZE:5}
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


