cpo:
  jwt:
    signing-key: aEVOb1ROdDdkaU5rdm03V3ZpVXoyUVZ1U3NmY0VjdWJD
    issuer: dnNwLWNwbw==
  services:
    enhancer:
      uri: ${ENHANCER_URL}

spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: AUTH

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
    jmx:
      exposure:
        include: "*"