apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtw
  namespace: cpo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gtw
  template:
    metadata:
      name: gtw-pod
      labels:
        app: gtw
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: gtw-container
          image: adu.lan/cpo/cpo-gateway:latest
          imagePullPolicy: Always
          ports:
            - name: gtw-p
              containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /availability/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /availability/ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          env:
            - name: PROCESSOR_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: processor-uri
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: auth-uri
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - gtw
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - sierra