apiVersion: v1
kind: ConfigMap
metadata:
  name: cpo-config
  namespace: cpo
data:
  pg-service: "pg-db-svc-ext"
  pg-max-pool-size: "7"
  caller-uri: "http://caller-svc.cpo.svc.cluster.local:8080"
  enhancer-uri: "http://enhancer-svc.cpo.svc.cluster.local:8080"
  gateway-uri: "http://gateway-svc.cpo.svc.cluster.local:8080"
  localization-uri: "http://localization-svc.cpo.svc.cluster.local:8080"
  notification-uri: "http://notification-svc.cpo.svc.cluster.local:8080"
  processor-uri: "http://processor-svc.cpo.svc.cluster.local:8080"